WITH CUSTOMER_REVENUE AS (
    SELECT
        CUSTOMER_ID,
        CUSTOMER_NAME,
        ROUND(SUM(TOTAL_REVENUE),3) AS TOTAL_REVENUE_BY_CUSTOMER
    FROM
    {{ref('outer_join')}}
    GROUP BY CUSTOMER_ID,CUSTOMER_NAME
)
SELECT 
    *,
    RANK() OVER( ORDER BY TOTAL_REVENUE_BY_CUSTOMER DESC) AS RANK
FROM 
CUSTOMER_REVENUE