WITH PRODUCT_REVENUE AS (
    SELECT
        PRODUCT_ID,
        SUM(TOTAL_REVENUE) AS TOTAL_REVENUE_BY_PRODUCT
    FROM
    {{ref('outer_join')}}
    GROUP BY PRODUCT_ID
)
SELECT 
    *,
    RANK() OVER( ORDER BY TOTAL_REVENUE_BY_PRODUCT DESC) AS RANK
FROM 
PRODUCT_REVENUE